#!/usr/bin/env bash
#SBATCH -p formal-6226R
#SBATCH -N 4
#SBATCH --cpus-per-task=32
#SBATCH --ntasks-per-node=1
#SBATCH -J qsgw-refresh
#SBATCH --mem=256000

set -euo pipefail

# Template: refreshed-head-wing qsgw_band0 continuation loop.
#
# Intended use:
#   1. Complete the initial ABACUS SCF -> PyATB -> NSCF -> preprocess stages.
#   2. Keep librpa.qsgw_band0.in as the base input.
#   3. Provide qsgw_refresh_headwing_cmd in env.sh. The command must read:
#        QSGW_COMPLETED_ITERATION, QSGW_COMPLETED_ITERATION4,
#        QSGW_NEXT_ITERATION, QSGW_HR_PATTERN
#      and update pyatb_librpa_df/ from the exported QSGW HR without replacing
#      root ABACUS files such as band_out, k_path_info, velocity_matrix, or
#      KS_eigenvector_*.dat.
#   4. Submit this script through Slurm. Do not run production workloads on a
#      login node.

usage() {
  cat <<'EOF'
Usage:
  run_qsgw_headwing_refresh_loop.sh

Required environment:
  librpa_work or OH_MY_LIBRPA_LIBRPA_EXEC
  qsgw_refresh_headwing_cmd

Common optional environment:
  qsgw_max_iter=20
  qsgw_start_iteration=<integer>
  qsgw_base_librpa_input=librpa.qsgw_band0.in
  qsgw_output_dir=librpa.d
  libri_mpi_ranks=<integer>
  omp_threads=<integer>

This script is a Slurm-oriented template. It refuses to run outside a Slurm
allocation unless allow_local_qsgw_refresh_loop=1 is set for a local smoke test.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ -f ./env.sh ]]; then
  # shellcheck disable=SC1091
  source ./env.sh
fi

python3_exec="${python3_exec:-${OH_MY_LIBRPA_PYTHON3_EXEC:-python3}}"
librpa_work="${librpa_work:-${OH_MY_LIBRPA_LIBRPA_EXEC:-}}"
mpirun_exec="${mpirun_exec:-${OH_MY_LIBRPA_MPI_LAUNCHER_CMD:-mpirun}}"
libri_mpi_ranks="${libri_mpi_ranks:-${mpi_ranks:-4}}"
omp_threads="${omp_threads:-${SLURM_CPUS_PER_TASK:-32}}"
qsgw_max_iter="${qsgw_max_iter:-20}"
qsgw_output_dir="${qsgw_output_dir:-librpa.d}"
qsgw_base_librpa_input="${qsgw_base_librpa_input:-librpa.qsgw_band0.in}"
qsgw_restart_dir="${qsgw_restart_dir:-$qsgw_output_dir/qsgw_checkpoints/}"
qsgw_iteration_records_dir="${qsgw_iteration_records_dir:-qsgw_iteration_records}"
qsgw_refresh_stamps_dir="${qsgw_refresh_stamps_dir:-qsgw_refresh_stamps}"
qsgw_refresh_headwing_cmd="${qsgw_refresh_headwing_cmd:-}"
allow_local_qsgw_refresh_loop="${allow_local_qsgw_refresh_loop:-0}"

export OMP_NUM_THREADS="$omp_threads"

require_exec() {
  local path="$1"
  local label="$2"
  if [[ "$path" == */* ]]; then
    [[ -x "$path" ]] || { echo "Missing executable for $label: $path" >&2; exit 1; }
    return 0
  fi
  command -v "$path" >/dev/null 2>&1 || { echo "Executable for $label not found in PATH: $path" >&2; exit 1; }
}

require_file() {
  local path="$1"
  [[ -f "$path" ]] || { echo "Missing required file: $path" >&2; exit 1; }
}

require_dir() {
  local path="$1"
  [[ -d "$path" ]] || { echo "Missing required directory: $path" >&2; exit 1; }
}

require_glob() {
  local pattern="$1"
  compgen -G "$pattern" >/dev/null || { echo "Missing required files matching: $pattern" >&2; exit 1; }
}

iter4() {
  printf '%04d' "$1"
}

iter5() {
  printf '%05d' "$1"
}

latest_completed_iteration() {
  if [[ -n "${qsgw_start_iteration:-}" ]]; then
    printf '%s\n' "$qsgw_start_iteration"
    return 0
  fi
  if [[ -f latest_iteration.txt ]]; then
    tr -d '[:space:]' < latest_iteration.txt
    return 0
  fi
  printf '0\n'
}

write_librpa_input() {
  local target_iter="$1"
  local restart_iter="$2"
  local tmp_input="librpa.in.next.$$"

  require_file "$qsgw_base_librpa_input"
  awk '
    BEGIN { IGNORECASE = 1 }
    /^[[:space:]]*(max_iter|qsgw_restart|qsgw_restart_dir|qsgw_restart_iteration)[[:space:]=]/ { next }
    { print }
  ' "$qsgw_base_librpa_input" > "$tmp_input"

  {
    printf '\n# Generated by run_qsgw_headwing_refresh_loop.sh\n'
    printf 'max_iter = %s\n' "$target_iter"
    if (( restart_iter > 0 )); then
      printf 'qsgw_restart = t\n'
      printf 'qsgw_restart_dir = %s\n' "$qsgw_restart_dir"
      printf 'qsgw_restart_iteration = %s\n' "$restart_iter"
    fi
  } >> "$tmp_input"

  mv "$tmp_input" librpa.in
}

archive_iteration() {
  local completed_iter="$1"
  local completed4
  local dest
  completed4="$(iter4 "$completed_iter")"
  dest="$qsgw_iteration_records_dir/iter_$completed4"
  mkdir -p "$dest"

  cp -f librpa.in "$dest/librpa.in" 2>/dev/null || true
  cp -f "LibRPA.qsgw_iter_${completed4}.out" "$dest/" 2>/dev/null || true
  cp -f QSGW_band_spin_* "$dest/" 2>/dev/null || true
  cp -f GW_band_spin_* "$dest/" 2>/dev/null || true
  cp -f "hrs"*"_nao_qsgw_iter_${completed4}.csr" "$dest/" 2>/dev/null || true
  cp -f librpa_para_nprocs_*_myid_0.out "$dest/" 2>/dev/null || true
}

verify_qsgw_iteration() {
  local completed_iter="$1"
  local completed4 completed5 checkpoint_dir
  completed4="$(iter4 "$completed_iter")"
  completed5="$(iter5 "$completed_iter")"
  checkpoint_dir="$qsgw_restart_dir/iter_${completed5}"

  require_dir "$checkpoint_dir"
  require_glob "$checkpoint_dir/H0_GW_spin_*.bin"
  require_glob "hrs*_nao_qsgw_iter_${completed4}.csr"
  require_glob 'QSGW_band_spin_*'
}

refresh_headwing_from_iteration() {
  local completed_iter="$1"
  local next_iter="$2"
  local completed4 stamp
  completed4="$(iter4 "$completed_iter")"
  stamp="$qsgw_refresh_stamps_dir/headwing_ready_after_iter_${completed4}.stamp"

  if [[ -f "$stamp" ]]; then
    echo "Head-wing refresh already stamped for iteration $completed_iter: $stamp"
    return 0
  fi

  if [[ -z "$qsgw_refresh_headwing_cmd" ]]; then
    echo "Missing qsgw_refresh_headwing_cmd. Set it in env.sh for this material." >&2
    exit 1
  fi

  require_glob "hrs*_nao_qsgw_iter_${completed4}.csr"
  export QSGW_COMPLETED_ITERATION="$completed_iter"
  export QSGW_COMPLETED_ITERATION4="$completed4"
  export QSGW_NEXT_ITERATION="$next_iter"
  export QSGW_HR_PATTERN="hrs*_nao_qsgw_iter_${completed4}.csr"

  echo "Refreshing PyATB/head-wing from QSGW HR iteration $completed_iter"
  bash -lc "$qsgw_refresh_headwing_cmd"
  require_dir pyatb_librpa_df
  require_file pyatb_librpa_df/band_out
  require_glob 'pyatb_librpa_df/KS_eigenvector_*.dat'

  mkdir -p "$qsgw_refresh_stamps_dir"
  date -u '+%Y-%m-%dT%H:%M:%SZ' > "$stamp"
}

if [[ -z "${SLURM_JOB_ID:-}" && "$allow_local_qsgw_refresh_loop" != "1" ]]; then
  echo "This template is intended for a Slurm allocation. Set allow_local_qsgw_refresh_loop=1 only for a local smoke test." >&2
  exit 1
fi

[[ -n "$librpa_work" ]] || { echo 'Missing librpa_work; set it in env.sh or export OH_MY_LIBRPA_LIBRPA_EXEC.' >&2; exit 1; }
require_exec "$python3_exec" python3_exec
require_exec "$librpa_work" librpa_work
require_exec "$mpirun_exec" mpirun_exec
require_file "$qsgw_base_librpa_input"

mkdir -p "$qsgw_iteration_records_dir" "$qsgw_refresh_stamps_dir"

completed_iter="$(latest_completed_iteration)"
[[ "$completed_iter" =~ ^[0-9]+$ ]] || { echo "Invalid completed iteration: $completed_iter" >&2; exit 1; }
[[ "$qsgw_max_iter" =~ ^[0-9]+$ ]] || { echo "Invalid qsgw_max_iter: $qsgw_max_iter" >&2; exit 1; }

echo "Begin QSGW refresh loop: $(date)"
echo "completed_iter=$completed_iter qsgw_max_iter=$qsgw_max_iter"
echo "librpa_work=$librpa_work"
echo "mpirun_exec=$mpirun_exec libri_mpi_ranks=$libri_mpi_ranks OMP_NUM_THREADS=$OMP_NUM_THREADS"

if (( completed_iter > 0 && completed_iter < qsgw_max_iter )); then
  refresh_headwing_from_iteration "$completed_iter" "$((completed_iter + 1))"
fi

while (( completed_iter < qsgw_max_iter )); do
  target_iter="$((completed_iter + 1))"
  target4="$(iter4 "$target_iter")"
  log_file="LibRPA.qsgw_iter_${target4}.out"

  write_librpa_input "$target_iter" "$completed_iter"
  echo "Running qsgw_band0 target iteration $target_iter"
  OMP_NUM_THREADS="$omp_threads" "$mpirun_exec" -np "$libri_mpi_ranks" "$librpa_work" >> "$log_file"

  verify_qsgw_iteration "$target_iter"
  archive_iteration "$target_iter"
  completed_iter="$target_iter"
  printf '%s\n' "$completed_iter" > latest_iteration.txt

  if grep -R "Converged after .* iterations" "$log_file" librpa_para_nprocs_*_myid_0.out 2>/dev/null; then
    echo "QSGW convergence marker found after iteration $completed_iter"
    break
  fi

  if (( completed_iter < qsgw_max_iter )); then
    refresh_headwing_from_iteration "$completed_iter" "$((completed_iter + 1))"
  fi
done

echo "End QSGW refresh loop: $(date)"
